version: 2.1

orbs:
  cypress: cypress-io/cypress@3
  node: circleci/node@5.0.2

workflows:
  build:
    jobs:
      - cypress/run:
          node-version: '18.17.0'
          start-command: 'npm run start'
          pre-steps:
            - node/install:
                node-version: '18.17.0'
            - run: node --version