name: Build and Test 
run-name: ${{ github.actor }} is testing out 🚀
on: 
  pull-request: 
    branches : [main]

strategy:
  matrix:
    node-version: ['18.x', '20.x']


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Chekcout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

    - name: Run build script
      run: npm run build

    - name: Test
      run: npm run test